#' Load required libraries.
library(xts)
library(dplyr)
library(dygraphs)
library(shiny)
library(RColorBrewer)
library("testthat")
library("ggplot2")
library("reshape2")

#' Define parameters of the powerwall battery.
powerwall_spec = list(
  model = "Tesla Powerwall April 2016",
  capacity = 6.4, # [kWh]
  efficiency = 0.925, #round-trip DC efficiency
  power_nominal = 3.3, # [kW]
  voltage_nominal = 350, # [Volts]
  voltage_range = c(350, 450), # [Volts]
  current_nominal = 9.5, # [Amp]
  cost = 3000 # [EUR]
)

# Use Powerwall battery
battery_spec <- powerwall_spec

#' Load data from available files
#+ datasets, cache=TRUE
# energy_demand_profiles <- read.table("Data/data1.csv", header = FALSE, sep = ";")
#generation_normalized <- read.table("Data/pv30minsgen.csv", header = FALSE)[[1]]

#' Calculate energy balance for a single year.
#' @param energy_demand_profile Energy demand profile for a single year.
#' @param pv_array_energy_output Energy generated by the PV system for a single year (before the inverter).
#' @param inverter_spec Inverter specification.
#' @param battery_spec Battery specification.
calculate_yearly_energy_balance <- function(
  energy_demand_profile,
  pv_array_energy_output,
  inverter_spec,
  battery_spec) {
  
  #' Simulate charge/discharge cycles of the battery for the demand profile
  #+ simulation, cache=TRUE
  n <- length(energy_demand_profile)
  period <- 1 / (n / 365 / 24) # [h]
  energy_imported <- rep(0, n) # [kWh]
  battery_energy <- rep(0, n) # [kWh]
  battery_energy_next <- rep(0, n) # [kWh]
  battery_diff <- rep(0, n) # [kWh]
  battery_roundtrip_loss <- rep(0, n) # [kWh]
  inverter_input <- rep(0, n) # [kWh]
  inverter_output <- rep(0, n) # [kWh]
  inverter_loss <- rep(0, n) # [kWh]
  energy_diff <- rep(0, n) # [kWh]
  
  for (i in 1:n) {
    # Battery_energy starts as zero and flows from battery_energy_next variable
    battery_energy[i] <- if (i == 1) 0 else battery_energy_next[i - 1] # [kWh]
    
    # Start with energy demand matching the energy demand profile 
    ac_demand <- energy_demand_profile[i] # [kWh]
    dc_demand <- ac_demand / inverter_spec$efficiency # [kWh]
    dc_diff <- dc_demand - pv_array_energy_output[i] # [kWh]
    
    if (dc_diff > 0) {
      # Demand was higher than what was generated. We need to get more energy.
      
      if (battery_energy[i] > 0) {
        # Batter is not empty. We can use this energy.
        
        # Discharge the battery, but make sure the discharge power is lower than the nominal power.
        battery_diff[i] <- min(dc_diff, battery_energy[i], battery_spec$power_nominal * period) # [kWh]
        
        # Take energy from battery
        battery_energy_next[i] <- battery_energy[i] - battery_diff[i] # [kWh]
        
        inverter_input[i] <- pv_array_energy_output[i] + battery_diff[i] # [kWh]
      } else {
        # Battery is empty. Inverter input matches PV array energy output.
        
        inverter_input[i] <- pv_array_energy_output[i] # [kWh]
        battery_energy_next[i] <- battery_energy[i] # [kWh]
      }
    } else {
      # Demand was lower than what was generated. We can save the extra energy.
      
      if (battery_energy[i] < battery_spec$capacity) {
        # Battery is not full. We can save some energy in the battery.
        
        # Charge the battery, but make sure there is no overcharging.
        battery_diff[i] <- max(
          - (battery_spec$capacity - battery_energy[i]) / battery_spec$efficiency,
          dc_diff) # [kWh]
        
        # Save energy in the battery
        battery_energy_next[i] <- battery_energy[i] - battery_diff[i] * battery_spec$efficiency # [kWh]
        battery_roundtrip_loss[i] <- - battery_diff[i] * (1 - battery_spec$efficiency) # [kWh]
        
        inverter_input[i] <- pv_array_energy_output[i] + battery_diff[i] # [kWh]
      } else {
        # Battery is full. We need to sell extra energy to the grid.
        
        inverter_input[i] <- pv_array_energy_output[i] # [kWh]
        battery_energy_next[i] <- battery_energy[i] # [kWh]
      }
    }
    
    inverter_output[i] <- inverter_input[i] * inverter_spec$efficiency # [kWh]
    inverter_loss[i] <- inverter_input[i] * (1 - inverter_spec$efficiency) # [kWh]
    
    # Energy difference between demand and generated (after inverter).
    energy_diff[i] <- ac_demand - inverter_output[i] # [kWh]
  }
  
  # Check the sign to tell if the ennergy difference is for import or export.
  energy_imported <- ifelse(energy_diff > 0, energy_diff, 0) # [kWh]
  energy_exported <- ifelse(energy_diff < 0, -energy_diff, 0) # [kWh]
  
  # Gather all values in a signel data frame
  return(data.frame(
    pv_array_energy_output,
    energy_demand_profile,
    inverter_loss,
    battery_roundtrip_loss,
    battery_energy_next,
    battery_energy,
    energy_diff,
    energy_imported,
    energy_exported,
    battery_diff,
    battery_percentage = if (battery_spec$capacity > 0) battery_energy / battery_spec$capacity * 100 else 0))
}

#' Calculate energy balance for a complete lifetime of the system.
#' @param energy_demand_profile Energy demand profile for a single year.
#' @param pv_array_energy_output Energy generated by the PV system for a single year (before the inverter).
#' @param inverter_spec Inverter specification.
#' @param battery_spec Battery specification.
#' @param pv_module_spec PV module specification.
#' @param lifetime_length lifetime length in years.
calculate_lifetime_energy_balance <- function(
  energy_demand_profile,
  pv_array_energy_output,
  inverter_spec,
  battery_spec,
  pv_module_spec,
  lifetime_length) {
  
  balance <- data.frame()
  for (year in 1:lifetime_length) {
    # Adjust pv output according to the deterioration curve from the specification. Specify rule = 2
    # in the approx function to use the lowest guaranteed value for years outside of the period
    # mentioned in the specification.
    pv_array_energy_output_deteriorated <- pv_array_energy_output *
      approx(pv_module_spec$deterioration_curve$year, pv_module_spec$deterioration_curve$guarantee, year, rule = 2)$y
    
    balance_yearly <- calculate_yearly_energy_balance(
      energy_demand_profile,
      pv_array_energy_output_deteriorated,
      inverter_spec,
      battery_spec)
    balance_yearly$year <- year
    
    balance <- rbind(balance, balance_yearly)
  }
  
  return(balance)
}


calculate_cashflow_summary <- function(
  energy_balance,
  pv_array_spec,
  battery_spec) {
  
  # Residential elecrticity prices SEAI Q1 2015
  energy_prices_residential <- data.frame(
    band = c("DA", "DB", "DC", "DD", "DE"),
    band_range = c("< 1e+03", "(1e+03,2.5e+03]", "(2.5e+03,5e+03]", "(5e+03,1.5e+04]", "1.5e+04 <"),
    price = c(0.697, 0.310, 0.243, 0.204, 0.174),
    price_change = c(0.048, -0.035, -0.043, -0.066, -0.047))
  energy_consumption_band <- as.numeric(cut(sum(energy_balance$energy_demand_profile), c(0, 1000, 2500, 5000, 15000, 10e6)))
  
  # Assume constant price of the imported energy
  #tariff_import_change <- energy_prices_residential$price_change[energy_consumption_band] # change / year
  tariff_import_change <- 0 # change / year
  
  estimated_system_unit_cost <- 3 * pv_array_spec$capacity ^ (-0.537) # EUR / Wp
  estimated_system_cost <- estimated_system_unit_cost * pv_array_spec$capacity * 1000 # EUR
  initial_cost <- estimated_system_cost + battery_spec$cost

  # Maintainance cost takes into account inverter replacement
  maintenance_ratio = 0.01 # 1% of CAPEX without the battery
  maintenance_cost <- maintenance_ratio * (initial_cost - battery_spec$cost) # EUR/year
  
  cashflow_summary <- energy_balance %>%
    group_by(year) %>%
    summarize_each(funs="sum") %>%
    arrange(year) %>%
    mutate(
      energy_consumption_band = as.numeric(cut(energy_demand_profile, c(0, 1000, 2500, 5000, 15000, 10e6))),
      tariff_import = energy_prices_residential$price[energy_consumption_band] * (1 + tariff_import_change) ^ (year - 1), # EUR
      tariff_export = 0 # EUR
    ) %>%
    transmute(
      year,
      energy_demand = energy_demand_profile,
      energy_demand_covered = energy_demand - energy_imported,
      energy_imported,
      energy_exported,
      tariff_import,
      tariff_export,
      inflow_export = tariff_export * energy_exported,
      # Energy exported is considered as a saving because it results in recuded bill from the energy
      # supplier.
      inflow_saving = tariff_import * energy_demand_covered + tariff_export * energy_exported,
      outflow_import = tariff_import * energy_imported,
      outflow_maintainence = maintenance_cost,
      # Inflow comes purely from savings.
      inflow = inflow_saving,
      # Outflow comes from maintainence cost ast the cost of imported energy are unrelated to the
      # investment.
      outflow = outflow_maintainence
    ) %>%
    # Associate initial cost with the pseudo-year zero. 
    bind_rows(data.frame(year = 0, cashflow_investment = initial_cost)) %>%
    arrange(year)
  
  # Replace NA values with zeros for the pseudo-year and column cashflow_investment
  cashflow_summary[is.na(cashflow_summary)] <- 0
  
  # Calculate the final cashflows
  cashflow_summary <- cashflow_summary %>%
    mutate(
      net_cashflow = inflow - outflow - cashflow_investment,
      net_cashflow_cumulative = cumsum(net_cashflow)
    )
  
  return(cashflow_summary)
}

discount <- function(value, rate) {
  value / (1 + rate) ^ (seq_along(value) - 1)
}

calculate_npv <- function(simulation_result, pv_array_size) {
  # Real discount rate
  discount_rate <- 0.08 # -
  
  npv_table <- create_npv_table(simulation_result, pv_array_size)
  
  npv <- ceiling(sum(npv_table$net_cashflow / (1 + discount_rate) ^ npv_table$year_index))
  
  positive_year <- npv_table$year_index[npv_table$cumulative_balance > 0]
  spp <- if (length(positive_year) > 0) min(positive_year) else NA
  
  lcoe <- 
    sum(discount(
      npv_table$cashflow_investment + npv_table$outflow_maintainence, 
      discount_rate)) / 
    sum(discount(
      (npv_table$energy_demand - npv_table$energy_imported) + npv_table$energy_exported,
      discount_rate))
  
  sir <- 
    sum(discount(npv_table$inflow - npv_table$outflow, discount_rate))  /
    sum(npv_table$cashflow_investment)

  # Find the first year (min) where (which) cumulative (cumsum) discounted (dicount)
  # balance is higher than zero or return NA if such year would exceed the lifetime.
  dpp <- min(c(NA, which(
    0 < cumsum(discount(npv_table$inflow - npv_table$outflow - npv_table$cashflow_investment, discount_rate)))))
    
  return(list(npv = npv, spp = spp, lcoe = lcoe, sir = sir, dpp = dpp))
}

#' Reads solar radiation.
read_radiation <- function(direction) {
  radiation_part <- read.delim(sprintf("Data/Radiation_0.5h_Article/Radiation_Power_%s.out", direction), header=FALSE, skip = 2)
  # Ignore hour column
  radiation_part[[1]] <- NULL
  # Ignore last column
  radiation_part[[8]] <- NULL
  # Select only one year
  radiation_part <- radiation_part[1:17520, ]
  # Set the right names
  names(radiation_part) <- c("20", "25", "30", "35", "40", "45", "50")
  # Convert from [kJ/ (h * m^2)] to [kW / m^2]
  radiation_part <- radiation_part / 3600
  return(radiation_part)
}

#' Calculates standard economical indicators.
#' @param cashflow_summary Summary retrned by calculate_cashflow_summary function.
calculate_economical_indicators <- function(cashflow_summary) {
  # Real discount rate
  discount_rate <- 0.08 # -
  
  npv <- ceiling(sum(cashflow_summary$net_cashflow / (1 + discount_rate) ^ cashflow_summary$year))
  
  positive_year <- cashflow_summary$year[cashflow_summary$net_cashflow_cumulative > 0]
  spp <- if (length(positive_year) > 0) min(positive_year) else NA
  
  lcoe <- 
    sum(discount(
      cashflow_summary$cashflow_investment + cashflow_summary$outflow_maintainence, 
      discount_rate)) / 
    sum(discount(
      (cashflow_summary$energy_demand - cashflow_summary$energy_imported) + cashflow_summary$energy_exported,
      discount_rate))
  
  sir <- 
    sum(discount(cashflow_summary$inflow - cashflow_summary$outflow, discount_rate))  /
    sum(cashflow_summary$cashflow_investment)
  
  # Find the first year (min) where (which) cumulative (cumsum) discounted (dicount)
  # balance is higher than zero or return NA if such year would exceed the lifetime.
  dpp <- min(c(NA, which(
    0 < cumsum(discount(cashflow_summary$inflow - cashflow_summary$outflow - cashflow_summary$cashflow_investment, discount_rate)))))
  
  return(list(npv = npv, spp = spp, lcoe = lcoe, sir = sir, dpp = dpp))
}